kanguru/customers/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextField, PasswordField, SubmitField, BooleanField
from wtforms.validators import DataRequired
from datetime import datetime


class LoginForm(FlaskForm):
    username = StringField('Nazwa',
                           validators=[DataRequired()])
    password = PasswordField('Haslo',
                             validators=[DataRequired()])
    remember = BooleanField('Pamietaj mnie')
    submit = SubmitField('Login')


class CustomerForm(FlaskForm):
    details = StringField('Detale', validators=[DataRequired()])
    submit = SubmitField('Dodaj')


class SearchForm(FlaskForm):
    details = TextField()
    submit = SubmitField('Szukaj')

kanguru/customers/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from kanguru import db, bcrypt
from flask_login import login_user, current_user, logout_user, login_required
from kanguru.customers.forms import LoginForm, CustomerForm, SearchForm
from kanguru.interactions.forms import InteractionForm
from kanguru.models import Customer, Interaction, Employee
from sqlalchemy.sql import func
from datetime import datetime, timedelta


bp_customers = Blueprint('customers', __name__)

rows_per_page = 20


@bp_customers.route("/", methods=['GET', 'POST'])
@bp_customers.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('customers.customers'))
    form = LoginForm()
    if form.validate_on_submit():
        employee = Employee.query.filter_by(username=form.username.data).first()
        if employee and bcrypt.check_password_hash(employee.password, form.password.data):
            login_user(employee, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('customers.customers'))
        else:
            flash('Login Unsuccessful. Please check username and password', 'danger')
    return render_template('login.html', title='Login', form=form)


@bp_customers.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('customers.login'))


@bp_customers.route("/customers", methods=['GET', 'POST'])
@login_required
def customers():
    form = SearchForm()
    page = request.args.get('page', 1, type=int)
    if form.details.data is not None:
        # customers = db.engine.execute("""SELECT c.id
        #                                             ,c.details
        #                                             ,COALESCE(SUM(i.paid-i.bill),0)
        #                                        FROM customer c
        #                                   LEFT JOIN interaction i
        #                                          ON c.id = i.customer_id
        #                                       WHERE c.details LIKE '%""" + str(form.details.data).replace("'", "").replace('"', '') + """%'
        #                                    GROUP BY c.id, c.details
        #                                    ORDER BY c.details ASC""")

        customers = db.session.query(Customer.id, Customer.details, func.coalesce(func.sum(Interaction.paid - Interaction.bill), 0).label('debt'))\
            .outerjoin(Interaction, Interaction.customer_id == Customer.id)\
            .filter(Customer.details.like('%' + form.details.data + '%'))\
            .group_by(Customer.details, Customer.id)\
            .order_by(Customer.details.desc())\
            .paginate(page=1, per_page=rows_per_page)
    else:

        customers = db.session.query(Customer.id, Customer.details, func.coalesce(func.sum(Interaction.paid - Interaction.bill), 0).label('debt'))\
            .outerjoin(Interaction, Interaction.customer_id == Customer.id)\
            .group_by(Customer.details, Customer.id)\
            .order_by(Customer.details.desc())\
            .paginate(page=page, per_page=rows_per_page)
        # customers = db.engine.execute("""SELECT c.id
        #                                        ,c.details
        #                                        ,COALESCE(SUM(i.paid-i.bill),0) AS debt
        #                                    FROM customer c
        #                               LEFT JOIN interaction i
        #                                      ON c.id = i.customer_id
        #                                GROUP BY c.id, c.details
        #                                ORDER BY c.details ASC""")

    return render_template('customers.html', title='Klient', customers=customers, form=form)


def calc_debt(customer_id):
    bill = db.session.query(func.coalesce(func.sum(Interaction.bill), 0)).filter(Interaction.customer_id == customer_id).first()
    paid = db.session.query(func.coalesce(func.sum(Interaction.paid), 0)).filter(Interaction.customer_id == customer_id).first()

    try:
        debt = paid[0] - bill[0]
    except:
        debt = 0

    return debt


@bp_customers.route("/add_customer", methods=['GET', 'POST'])
@login_required
def add_customer():
    form = CustomerForm()
    if form.validate_on_submit():
        new_customer = Customer(details=form.details.data)
        db.session.add(new_customer)
        db.session.commit()
        return redirect(url_for('customers.customers'))
    return render_template('add_customer.html', title='Dodaj klienta', form=form, legend='Dodaj klienta')


@bp_customers.route("/customer/<int:customer_id>")
@login_required
def customer(customer_id):
    customer = Customer.query.get_or_404(customer_id)
    debt = calc_debt(customer_id)

    lm_year = (datetime.now() - timedelta(days=datetime.now().day + 1)).year
    lm_month = (datetime.now() - timedelta(days=datetime.now().day + 1)).month

    lm_bill = db.session.query(func.coalesce(func.sum(Interaction.bill), 0)).filter(Interaction.customer_id == customer_id).filter(func.extract('year', Interaction.date) == lm_year).filter(func.extract('month', Interaction.date) == lm_month).first()
    lm_paid = db.session.query(func.coalesce(func.sum(Interaction.paid), 0)).filter(Interaction.customer_id == customer_id).filter(func.extract('year', Interaction.date) == lm_year).filter(func.extract('month', Interaction.date) == lm_month).first()

    try:
        lm_debt = lm_paid[0] - lm_bill[0]
    except:
        lm_debt = 0

    return render_template('customer.html', title=customer.details, customer=customer, debt=debt, lm_month=lm_month, lm_year=lm_year, lm_debt=lm_debt, lm_bill=lm_bill[0])


@bp_customers.route("/customer/<int:customer_id>/update", methods=['GET', 'POST'])
@login_required
def update_customer(customer_id):
    customer = Customer.query.get_or_404(customer_id)
    form = CustomerForm()
    if form.validate_on_submit():
        customer.details = form.details.data
        db.session.commit()
        flash('Dane klienta zmienione!', 'success')
        return redirect(url_for('customers.customer', customer_id=customer.id))
    elif request.method == 'GET':
        form.details.data = customer.details
    return render_template('add_customer.html', title='Zmiana danych klienta',
                           form=form, legend='Update klienta')


@bp_customers.route("/customer/<int:customer_id>/delete", methods=['POST'])
@login_required
def delete_customer(customer_id):
    customer = Customer.query.get_or_404(customer_id)
    db.session.delete(customer)
    db.session.commit()
    flash('Klient usuniety!', 'success')
    return redirect(url_for('customers.customers'))

kanguru/interactions/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from kanguru import app, db
from flask_login import login_required
from kanguru.interactions.forms import InteractionForm
from sqlalchemy.sql import func
from kanguru.models import Customer, Interaction

bp_interactions = Blueprint('interactions', __name__)

rows_per_page = 20


def calc_debt(customer_id):
    bill = db.session.query(func.coalesce(func.sum(Interaction.bill), 0)).filter(Interaction.customer_id == customer_id).first()
    paid = db.session.query(func.coalesce(func.sum(Interaction.paid), 0)).filter(Interaction.customer_id == customer_id).first()

    try:
        debt = paid[0] - bill[0]
    except:
        debt = 0

    return debt


@bp_interactions.route("/interactions/<int:interaction_id>/update", methods=['GET', 'POST'])
@login_required
def update_interaction(interaction_id):
    interaction = Interaction.query.get_or_404(interaction_id)
    form = InteractionForm()
    if form.validate_on_submit():
        interaction.details = form.details.data
        interaction.bill = form.bill.data
        interaction.paid = form.paid.data
        interaction.date = form.date.data
        db.session.commit()
        flash('Dane transakcji zmienione!', 'success')
        return redirect(url_for('interactions.customer_interactions', customer_id=interaction.customer_id))
    elif request.method == 'GET':
        form.details.data = interaction.details
        form.bill.data = interaction.bill
        form.paid.data = interaction.paid
        form.date.data = interaction.date
    return render_template('add_interaction.html', title='Zmiana transakcji',
                           form=form, legend='Update transakcji')


@bp_interactions.route("/interactions/<int:customer_id>")
@login_required
def customer_interactions(customer_id):
    page = request.args.get('page', 1, type=int)
    customer_interactions = Interaction.query.filter_by(customer_id=customer_id)\
        .order_by(Interaction.date.desc())\
        .paginate(page=page, per_page=rows_per_page)
    customer = Customer.query.get_or_404(customer_id)
    debt = calc_debt(customer_id)
    return render_template('customer_interactions.html',
                           title='Transakcje klienta',
                           interactions=customer_interactions,
                           customer=customer,
                           debt=debt)


@bp_interactions.route("/interactions/<int:customer_id>/new", methods=['GET', 'POST'])
@login_required
def add_interaction(customer_id):
    form = InteractionForm()
    customer = Customer.query.get_or_404(customer_id)
    if form.validate_on_submit():
        new_interaction = Interaction(details=form.details.data,
                                      customer_id=customer_id,
                                      date=form.date.data,
                                      bill=form.bill.data,
                                      paid=form.paid.data)
        db.session.add(new_interaction)
        db.session.commit()
        return redirect(url_for('interactions.customer_interactions', customer_id=customer.id))
    return render_template('add_interaction.html', title='Nowa transakcja',
                           form=form, legend='Nowa transakcja')


@bp_interactions.route("/interactions/<int:interaction_id>/delete", methods=['GET', 'POST'])
@login_required
def delete_interaction(interaction_id):
    interaction = Interaction.query.get_or_404(interaction_id)
    db.session.delete(interaction)
    db.session.commit()
    flash('Interakcja usunieta!', 'success')
    return redirect(url_for('interactions.customer_interactions', customer_id=interaction.customer_id))


@bp_interactions.route("/interactions/all_interactions_by_date")
@login_required
def all_interactions_by_date():
    page = request.args.get('page', 1, type=int)
    interactions = db.session.query(Interaction.id, Customer.details.label("customer_details"), Interaction.details, Interaction.bill, Interaction.paid, Interaction.date)\
        .outerjoin(Customer, Interaction.customer_id == Customer.id)\
        .order_by(Interaction.date.desc())\
        .paginate(page=1, per_page=rows_per_page)

    return render_template('all_interactions_by_date.html',
                           title='Wszystkie transakcje',
                           interactions=interactions)

kanguru/templates/add_customer.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">{{ legend }}</legend>
                <div class="form-group">
                    {{ form.details.label(class="form-control-label") }}
                    {% if form.details.errors %}
                        {{ form.details(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.details.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.details(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
{% endblock content %}

kanguru/templates/add_employee.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Add new employee</legend>
                <div class="form-group">
                    {{ form.username.label(class="form-control-label") }}

                    {% if form.username.errors %}
                        {{ form.username(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.username.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.username(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.confirm_password.label(class="form-control-label") }}
                    {% if form.confirm_password.errors %}
                        {{ form.confirm_password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.confirm_password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.confirm_password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-check">
                    {{ form.admin(class="form-check-input") }}
                    {{ form.admin.label(class="form-check-label") }}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
{% endblock content %}

kanguru/templates/add_interaction.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">{{ legend }}</legend>
                <div class="form-group">
                    {{ form.details.label(class="form-control-label") }}

                    {% if form.details.errors %}
                        {{ form.details(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.details.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.details(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.bill.label(class="form-control-label") }}

                    {% if form.bill.errors %}
                        {{ form.bill(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.bill.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.bill(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.paid.label(class="form-control-label") }}

                    {% if form.paid.errors %}
                        {{ form.paid(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.paid.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.paid(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.date.label(class="form-control-label") }}

                    {% if form.date.errors %}
                        {{ form.date(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.date.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.date(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
{% endblock content %}

kanguru/templates/all_interactions_by_date.html
{% extends "layout.html" %}
{% block content %}

    <div>
      <h4 class="text-left">Lista wszystkich transakcji</h4>
    </div>

    <table class="table">
    <thead>
      <tr>
        <th scope="col">Klient</th>
        <th scope="col">Data i godzina</th>
        <th scope="col">Opis</th>
        <th scope="col">Rachunek</th>
        <th scope="col">Zapłacono</th>
        <th scope="col">Akcje</th>
      </tr>
    </thead>
    <tbody>
    {% for interaction in interactions.items %}
       <tr>
       <td> {{ interaction.customer_details }} </td>
       <td> {{ interaction.date.strftime('%Y-%m-%d %H:%M') }} </td>
       <td> {{ interaction.details }} </td>
       <td> {{ interaction.bill }} </td>
       <td> {{ interaction.paid }} </td>
       <td>
          <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{ url_for('interactions.update_interaction', interaction_id=interaction.id) }}">Edytuj</a>
       </td>
     </tr>
    {% endfor %}
    </tbody>
    </table>
     {% for page_num in interactions.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
     {% if page_num %}
        {% if interactions.page == page_num %}
           <a  class="btn btn-info mb-4 " href="{{url_for('interactions.all_interactions_by_date', page=page_num)}}">{{ page_num }} </a>
        {% else %}
           <a  class="btn btn-outline-info mb-4 " href="{{ url_for('interactions.all_interactions_by_date', page=page_num)}}">{{ page_num }} </a>
        {% endif %}
     {% else %}
        ...
     {% endif %}
  {% endfor %}

{% endblock content %}

kanguru/templates/customer.html
{% extends "layout.html" %}
{% block content %}

    <div class="media-body">
      <div class="article-metadata">
          <div class='text-right'>
            <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{ url_for('customers.update_customer', customer_id=customer.id) }}">Zmień</a>
            <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal">Usuń</button>
          </div>
      </div>
      <h2 class="article-title"></h2>
      <h2 class="article-content"></h2>
      <h2 class="article-content"></h2>
      <h2 class="article-content"></h2>
      <h2 class="article-content"></h2>
      <h2 class="article-content"></h2>
    </div>


  <table class="table">
  <tbody>
    <tr>
      <th>{{ customer.details }}</th>
      <td></td>
    </tr>
    <tr>
      <th>Całkowity stan konta</th>
      <td>{{ debt }}</td>
    </tr>
    <tr>
      <th>Dług poprzedni miesiąc {{ lm_month }}    {{ lm_year }}</th>
      <td>{{lm_debt}}</td>
    </tr>
    <tr>
      <th>Rachunki poprzedni miesiąc {{ lm_month }}    {{ lm_year }}</th>
      <td>{{lm_bill}}</td>
    </tr>
  </tbody>
</table>

  <!-- Modal -->
  <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="deleteModalLabel">Usunąć klienta?</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <form action="{{ url_for('customers.delete_customer', customer_id=customer.id) }}" method="POST">
            <input class="btn btn-danger" type="submit" value="Delete">
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

kanguru/templates/customer_interactions.html
{% extends "layout.html" %}
{% block content %}
    <div class="text-right">
        <a class="btn btn-primary " href="{{ url_for('interactions.add_interaction', customer_id=customer.id) }}" role="button">Nowa transakcja</a>
    </div>

    <div>
      <h4 class="text-left">Lista akcji u klienta {{ customer.details }}</h4>
      <h4 class="text-left">Stan konta {{debt}}
    </div>

    <table class="table">
    <thead>
      <tr>
        <th scope="col">Data i godzina</th>
        <th scope="col">Opis</th>
        <th scope="col">Rachunek</th>
        <th scope="col">Zapłacono</th>
        <th scope="col">Akcje</th>
      </tr>
    </thead>
    <tbody>
    {% for interaction in interactions.items %}
       <tr>
       <td> {{ interaction.date.strftime('%Y-%m-%d %H:%M') }} </td>
       <td> {{ interaction.details }} </td>
       <td> {{ interaction.bill }} </td>
       <td> {{ interaction.paid }} </td>
       <td>
          <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{ url_for('interactions.update_interaction', interaction_id=interaction.id) }}">Edytuj</a>
       </td>
     </tr>

    {% endfor %}
    </tbody>
    </table>
     {% for page_num in interactions.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
     {% if page_num %}
        {% if interactions.page == page_num %}
           <a  class="btn btn-info mb-4 " href="{{url_for('interactions.customer_interactions', customer_id=customer.id, page=page_num)}}">{{ page_num }} </a>
        {% else %}
           <a  class="btn btn-outline-info mb-4 " href="{{ url_for('interactions.customer_interactions', customer_id=customer.id, page=page_num)}}">{{ page_num }} </a>
        {% endif %}
     {% else %}
        ...
     {% endif %}

  {% endfor %}
{% endblock content %}

kanguru/templates/customers.html
{% extends "layout.html" %}
{% block content %}
    <div class="text-right">
      <a class="btn btn-primary " href="{{ url_for('customers.add_customer') }}" role="button">Dodaj nowego klienta</a>
    </div>
    <div class="text-left">
      <h4>Lista klientów</h4>
    </div>
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
        <div class="form-group">

            {% if form.details.errors %}
                {{ form.details(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.details.errors %}
                        <span>{{ error }}</span>
                    {% endfor %}
                </div>
            {% else %}
                {{ form.details(class="form-control form-control-lg") }}
            {% endif %}
       </div>

        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info") }}
        </div>
    </form>

  <table class="table">
  <thead>
    <tr>
      <th scope="col">Opis klienta</th>
      <th scope="col">Stan konta</th>
      <th scope="col">Akcje</th>
    </tr>
  </thead>
  <tbody>
  {% for customer in customers.items %}
  <tr>
    <td> {{ customer.details}} </td>
    <td> {{ customer.debt}} </td>
    <td>
       <a class="btn btn-xs btn-info" href="{{url_for('interactions.customer_interactions', customer_id=customer.id)}}"role="button">Transakcje</a>
       <a class="btn btn-xs btn-info" href="{{url_for('customers.customer', customer_id=customer.id)}}" role="button">Detale</a>
    </td>
  </tr>
  {% endfor %}
  </tbody>
  </table>
  {% for page_num in customers.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
     {% if page_num %}
        {% if customers.page == page_num %}
           <a  class="btn btn-info mb-4 " href="{{ url_for('customers.customers', page=page_num)}}">{{ page_num }} </a>
        {% else %}
           <a  class="btn btn-outline-info mb-4 " href="{{ url_for('customers.customers', page=page_num)}}">{{ page_num }} </a>
        {% endif %}
     {% else %}
        ...
     {% endif %}
  {% endfor %}



{% endblock content %}

kanguru/templates/layout.html
<!DOCTYPE html>
<html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">

    {% if title %}
        <title>Kanguru - {{ title }}</title>
    {% else %}
        <title>Kanguru</title>
    {% endif %}
</head>
<body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="/">Kanguru</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              {% if current_user.is_authenticated %}
                 <a class="nav-item nav-link" href="{{ url_for('customers.customers') }}">Klienci</a>
                 <a class="nav-item nav-link" href="{{ url_for('interactions.all_interactions_by_date') }}">Transakcje</a>
              {% endif %}
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav mr-auto">
              {% if current_user.is_authenticated %}
                 <a class="nav-item nav-link" href="{{ url_for('customers.logout') }}">Wyloguj</a>
              {% endif %}
            </div>
          </div>
        </div>
      </nav>
    </header>
    <main role="main" class="container">
      <div class="row">
        <div class="col-md-8">
          {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
              {% for category, message in messages%}
                <div class="alert alert-{{ category }}">
                  {{ message }}
                </div>
              {% endfor %}
            {% endif %}
          {% endwith %}
          {% block content %}{% endblock %}

<!--         </div>
        {% if current_user.is_authenticated %}
          <div class="col-md-4">
            <div class="content-section">
              <h3>Our Sidebar</h3>
              <p class='text-muted'>You can put any information here you'd like.
                <ul class="list-group">
                  <li class="list-group-item list-group-item-light">Latest Posts</li>
                  <li class="list-group-item list-group-item-light">Announcements</li>
                  <li class="list-group-item list-group-item-light">Calendars</li>
                  <li class="list-group-item list-group-item-light">etc</li>
                </ul>
              </p>
            </div>
          </div>
        {% endif %}
      </div> -->
    </main>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>